severity: low
exclude:
  - message: Sourcemaps
    pattern: sourceMappingURL=data:application/json;base64,

  - message: Dependencies
    paths:
      - node_modules
      - venv
      - yarn-error.log
      - yarn.lock
